[versions]
api = "82"
appcompat = "1.6.1"
bcpkix-jdk18on = "1.77"
circleimageview = "3.1.0"
colorpickerview = "2.3.0"
constraintlayout = "2.1.4"
material = "1.11.0"

[libraries]
api = { module = "de.robv.android.xposed:api", version.ref = "api" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
bcpkix-jdk18on = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bcpkix-jdk18on" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
colorpickerview = { module = "com.github.skydoves:colorpickerview", version.ref = "colorpickerview" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }